name: Build and Release Assets

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Release Assets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole --add-data "settings.json:." modernizer.py
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-modernizer
          path: |
            dist/modernizer.exe       # For Windows
            dist/modernizer          # For Ubuntu and macOS

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-latest-modernizer
          path: ./artifacts/windows-latest

      - name: Download artifacts for Ubuntu
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-modernizer
          path: ./artifacts/ubuntu-latest

      - name: Download artifacts for macOS
        uses: actions/download-artifact@v3
        with:
          name: macos-latest-modernizer
          path: ./artifacts/macos-latest

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ./artifacts/windows-latest/modernizer.exe
            ./artifacts/ubuntu-latest/modernizer
            ./artifacts/macos-latest/modernizer
          tag: ${{ github.ref_name }}
          releaseName: Release ${{ github.ref_name }}
          body: |
            Release artifacts for Windows, Ubuntu, and macOS.
          token: ${{ secrets.GITHUB_TOKEN }}
