name: Build and Release Mac ARM64 App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Mac ARM64 App
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --add-data "settings.json:." modernizer.py

      - name: Archive the built app
        run: |
          mkdir -p dist/release
          mv dist/modernizer dist/release/modernizer-mac-arm64

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-arm64-app
          path: dist/release

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: mac-arm64-app
          path: dist/release

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/release/modernizer-mac-arm64"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes
            Release version ${{ github.ref_name }}.