name: Build macOS Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build macOS Release
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --add-data "settings.json:." modernizer.py

      - name: Archive build output
        run: |
          mkdir -p release
          mv dist/modernizer release/
          tar -czvf release/modernizer-mac.tar.gz -C release modernizer

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: modernizer-mac
          path: release/modernizer-mac.tar.gz
