name: Build and Release

on:
  push:
    tags:
      - "v*"  # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch:  # Allow manual trigger from GitHub Actions UI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --add-data "settings.json:." modernizer.py

      - name: Verify dist directory
        run: ls -R dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: modernizer-${{ matrix.os }}
          path: dist/*
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Verify downloaded artifacts
        run: ls -R artifacts

      - name: Compress artifacts
        run: zip -r artifacts/modernizer-${{ matrix.os }}.zip artifacts/modernizer-${{ matrix.os }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Multi-platform release of Text Modernizer.
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/modernizer-${{ matrix.os }}.zip
          asset_name: modernizer-${{ matrix.os }}.zip
          asset_content_type: application/zip
